// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfNlpS33zvV4Omn6PPJGJSAwdyC3N8zMc',
    appId: '1:822053210760:web:3548299a9c672d3500ad3d',
    messagingSenderId: '822053210760',
    projectId: 'dodidone-51d61',
    authDomain: 'dodidone-51d61.firebaseapp.com',
    storageBucket: 'dodidone-51d61.appspot.com',
    measurementId: 'G-4KL7T6TYEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNqb8l5Ots8cPs-w4OWbJT_l6MouMSvO4',
    appId: '1:822053210760:android:ca922d1b3d5e979800ad3d',
    messagingSenderId: '822053210760',
    projectId: 'dodidone-51d61',
    storageBucket: 'dodidone-51d61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2gFPqboMj8X3wWQ6ltx-elszqnh9_BpA',
    appId: '1:822053210760:ios:24a3c50264811a2f00ad3d',
    messagingSenderId: '822053210760',
    projectId: 'dodidone-51d61',
    storageBucket: 'dodidone-51d61.appspot.com',
    iosBundleId: 'com.example.zcDodiddone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2gFPqboMj8X3wWQ6ltx-elszqnh9_BpA',
    appId: '1:822053210760:ios:24a3c50264811a2f00ad3d',
    messagingSenderId: '822053210760',
    projectId: 'dodidone-51d61',
    storageBucket: 'dodidone-51d61.appspot.com',
    iosBundleId: 'com.example.zcDodiddone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfNlpS33zvV4Omn6PPJGJSAwdyC3N8zMc',
    appId: '1:822053210760:web:991d56fba28cb2ad00ad3d',
    messagingSenderId: '822053210760',
    projectId: 'dodidone-51d61',
    authDomain: 'dodidone-51d61.firebaseapp.com',
    storageBucket: 'dodidone-51d61.appspot.com',
    measurementId: 'G-SBZESQ3DF3',
  );
}